#!/Users/ntomlin/.nvm/versions/node/v8.2.1/bin/node

process.stdin.resume()

process.stdin.on('data', (buf) => {
  if (buf.byteLength < 5) { return }
  let content = buf.slice(4)

  let obj = {
    original: JSON.parse(content)
  }

  let reply = Buffer.from(JSON.stringify(obj))
  let length = Buffer.alloc(4)
  length.writeUInt32LE(reply.byteLength, 0)

  process.stdout.write(length)
  process.stdout.write(reply)
})
