#!/user/bin/env node

const net = require('net')
const portConfig = require('./port')

class Server {
  constructor ({ onData = function () {} }) {
    this.onData = onData
  }

  start () {
    this.server = net.createServer(con => this._handleConnection(con))

    this.server.on('error', (err) => {
      throw err
    })

    this.server.listen(0, '127.0.0.1', () => (
      portConfig.write(this.server.address().port)
    ))

    return this
  }

  stop () {
    portConfig.delete()
    this.server.close()
    this.connection.end()
  }

  _handleConnection (connection) {
    let data = ''

    connection.on('data', function (chunk) {
      data += chunk
    })

    connection.on('end', () => {
      if (data) {
        this.onData(data)
      }
      connection.end()
    })

    this.connection = connection
  }

  static start (...args) {
    return new Server(...args).start()
  }
}

module.exports = Server
