#!/user/bin/env node

const net = require('net')
const portConfig = require('./port')
const promisify = require('util.promisify')
const createServer = promisify(net.createServer)

class Server {
  connect () {
    this.server = createServer()
      .then(con => this._handleConnection(con))

    this.server.on('error', (err) => {
      throw err
    })

    this.server.listen(0, '127.0.0.1', () => (
      portConfig.write(this.server.address().port)
    ))

    return this
  }

  disconnect () {
    this.server.close()
    this.connection.end()
  }

  _handleConnection (connection) {
    let data = ''

    connection.on('data', function (chunk) {
      console.log('DATA!', chunk.toString)
      data += chunk
    })
    connection.on('end', () => {
      console.log('end!', data)
    })

    this.connection = connection
  }

  static connect () {
    return new Server().connect()
  }
}

module.exports = Server
